### ISSUE TITLE
Add response body to Yelp\Exception

### ISSUE THREAD

**Issue by staelche** [stevenmaguire/yelp-php#1]
Since debugging is really a mess right now it would make sense to add the response body to your exception.

Currently, you aren't able to get the original yelp error document by catching the yelp exception.

I would add a response attribute to your exception.

What do you think?

**Comment by stevenmaguire** [comment]
I am all for it. Submit a PR and let's take a look.

**Comment by stevenmaguire** [comment]
I've addressed this for you in #4. I will update the documentation and cut a release with a version bump shortly.

**Comment by stevenmaguire** [comment]
This is now merged and release. 

"stevenmaguire/yelp-php": "~1.1"

**Comment by staelche** [comment]
Seems like you were faster then me ;-)

Wanted to provide a pull request on the weekend.

Thanks anyway!

**Comment by stevenmaguire** [comment]
Ha, sorry. I had the project open and was taking care of some other things so I pressed forward. I would love for you to continue providing feedback and contribute some code!
