### ISSUE TITLE
Ratings

### ISSUE THREAD

**Issue by ghost** [stevenmaguire/yelp-php#19]
How to get ratings from Yelp with yelp-php ?

**Comment by stevenmaguire** [comment]
The [`getBusiness`](https://github.com/stevenmaguire/yelp-php/blob/master/src/Client.php#L170) method returns a business object, which according to the documentation includes some basic rating information. 

https://www.yelp.com/developers/documentation/v2/business

**Comment by ghost** [comment]
I need All the ratings, not some basic ratings. There are URLs in documentation for that. but there is no method for that ?

**Comment by stevenmaguire** [comment]
> There are URLs in documentation for that...

A link please?
