### ISSUE TITLE
Bad signature on getting business details

### ISSUE THREAD

**Issue by staelche** [stevenmaguire/yelp-php#2]
If I want to get the business with the id `yelp-san-francisco` then everything works just fine.

If I want to get the business with the id `xware42-gmbh-münchen-2` yelp tells me I sent a bad signature.

The exception:

```
n error occured querying YelpBusiness [Client error response [url] http://api.yelp.com/v2/business/xware42-gmbh-münchen-2 [status code] 400 [reason phrase] Bad Request]
```

The yelp response:

```
{"error": {"text": "Signature was invalid", "id": "INVALID_SIGNATURE", "description": "Invalid signature. Expected signature base string: GET\u0026http%3A%2F%2Fapi.yelp.com%2Fv2%2Fbusiness%2Fxware42-gmbh-m%25C3%25BCnchen-2\u0026oauth_consumer_key%3D...5dQ%26oauth_nonce%3D2e...1b3%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1429800095%26oauth_token%3D...gP4%26oauth_version%3D1.0"}}
```

Are you able to reproduce it? 

I can't imagine that this is a library problem but I have no clue what I am doing wrong on the other hand. Both searches and then the business retrieval is done with the same code...

**Comment by stevenmaguire** [comment]
I am able to reproduce it. The issue appears to be related to character encoding. 

The id of the business you are looking for is in fact `xware42-gmbh-münchen-2` which contains a special character, `ü`. 

When I look up a business by id `xware42-gmbh-münchen-2` I receive the error you've reported.

When I look up a business by id `xware42-gmbh-m%C3%BCnchen-2` I receive the expected response from the API.

I will look into a possible fix. If you have one in mind, branch and submit a PR.

**Comment by stevenmaguire** [comment]
I've got a solution in PR #3, I will merge and cut new release after it finishes building and reports code coverage and quality.

**Comment by stevenmaguire** [comment]
I've cut a new release with these fixes. Get the latest, update your package dependancies to require at least 1.0.7.

**Comment by staelche** [comment]
Perfect. Many thanks!
