### ISSUE TITLE
Get reviews from Yelp.

### ISSUE THREAD

**Issue by ghost** [stevenmaguire/yelp-php#21]
Hi, is there way with yelp-php to get reviews (all the reviews) for specific business ?

**Comment by stevenmaguire** [comment]
Try the next version of this package https://github.com/stevenmaguire/yelp-php/pull/20

**Comment by stevenmaguire** [comment]
@vladi160 did you try the version recommended above? I am interested in your experiences.

**Comment by stevenmaguire** [comment]
@vladi160 ????

**Comment by stevenmaguire** [comment]
tag 2.0.0 is now available with support for v3 api.
