### ISSUE TITLE
404 Not Found Response 

### ISSUE THREAD

**Issue by Mirza-Obaid** [stevenmaguire/yelp-php#22]
i have near 50 business ids. so i am looping there ids to get business reviews but after few records i am facing this issue .  what's the reason of this issue and what i am doing wrong i am using v3 of yelp 

> ClientException in RequestException.php line 113:                           
> Client error: `GET https://api.yelp.com/v3/businesses//reviews` resulted in a `404 Not Found` response:
> 
> {"error": {"code": "NOT_FOUND", "description": "Resource could not be found."}}

**Comment by stevenmaguire** [comment]
It looks like your business IDs are not making it into the method properly. 

Your error says `Client error: GET https://api.yelp.com/v3/businesses//reviews`; that is def a 404. 

The expected URL should be `https://api.yelp.com/v3/businesses/BUSINESS_ID/reviews`

Are you sure that your business ID's are not empty?

**Comment by Mirza-Obaid** [comment]
thank you for responding yes one of the id was not correct .now its working
