### ISSUE TITLE
Yelp API v2 Support Ending June 30, 2018

### ISSUE THREAD

**Issue by stevenmaguire** [stevenmaguire/yelp-php#24]
https://engineeringblog.yelp.com/2017/06/upcoming-deprecation-of-yelp-api-v2.html

This library currently supports v3 and v2. After the official deprecation by Yelp on June 30, 2018, this library will be updated to remove support for v2.

**Comment by sargbah84** [comment]
Hi Stevenmaguire, Yelp has already ended API v2 Support March 1st, 2018. My app is displaying error when I try to do an Api call to Yelp. 
https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going

**Comment by stevenmaguire** [comment]
@sargbah84 OAuth2 support for the Yelp API is documented as being removed today and judging from your comment, that appears to be the case. Now, you will need to use your API Key instead of Access Tokens to communicate with the API. You can read about that here: https://github.com/stevenmaguire/yelp-php#v3-client-example

The v2 (non "v3" Fusion) endpoints furnished by their API are documented as being removed on June 30, 2018. This issue is here as a reminder to remove support for `api.yelp.com/v2/` endpoints after June 30, 2018.

**Comment by sargbah84** [comment]
Hi Stevenmaguire, thank you for your quick response. I added the code below per the link you posted. However, I'm getting this error.

	public function __construct()
	{

		$this->options = array(
		    'accessToken' => 'YOUR ACCESS TOKEN', // Required, unless apiKey is provided
		    'apiHost' => 'api.yelp.com', // Optional, default 'api.yelp.com',
		    'apiKey' => env('YELP_KEY'), // Required, unless accessToken is provided
		);

		$this->client = \Stevenmaguire\Yelp\ClientFactory::makeWith(
		    $this->options,
		    \Stevenmaguire\Yelp\Version::THREE
		);

	}


Client error: `GET https://api.yelp.com/v3/businesses/the-westbean-coffee-roasters-san-diego-8?locale=en_US` resulted in a `401 Unauthorized` response:
{"error": {"code": "TOKEN_MISSING", "description": "An access token must be supplied in order to use this endpoint."}}

**Comment by stevenmaguire** [comment]
@sargbah84 It appears that this issue is not about v2 support, so in the interest of avoiding further confusion, can we move this discussion to #23 or a new issue?

**Comment by sargbah84** [comment]
@stevenmaguire , sure we can move it to another issue, thanks. I really appreciate it.
