### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by antonkurko** [stevenmaguire/yelp-php#9]
Hello. There was a problem in 17 Nov commit.
In /stevenmaguire/yelp-php/src/Client.php
Used this for Oauth:

``` php
$middleware = new Oauth1([
    'consumerKey'    => $this->consumerKey,
    'consumerSecret' => $this->consumerSecret,
    'token'           => $this->token,
    'tokenSecret'    => $this->tokenSecret
]);
```

there array key: **consumerKey, consumerSecret, tokenSecret**.

But in "guzzlehttp/oauth-subscriber" ver "~0.3":
/guzzlehttp/oauth-subscriber/src/Oauth1.php
string 62:

``` php
$this->config = [
    'version'          => '1.0',
    'request_method'   => self::REQUEST_METHOD_HEADER,
    'consumer_key'     => 'anonymous',
    'consumer_secret'  => 'anonymous',
    'signature_method' => self::SIGNATURE_METHOD_HMAC,
];
```

And string 242:

```
$key = rawurlencode($this->config['consumer_secret'])
    . '&' . rawurlencode($this->config['token_secret']);
```

there use array keys: **consumer_key, consumer_secret, token_secret**

Code generate notice:
PHP Notice:  Undefined index: token_secret in /.../vendor/guzzlehttp/oauth-subscriber/src/Oauth1.php on line 243
And ouath no work. Yelp return 403 forbidden error.

To fix this i need to change /stevenmaguire/yelp-php/src/Client.php (string 152):

``` php
$middleware = new Oauth1([
    'consumerKey'    => $this->consumerKey,
    'consumerSecret' => $this->consumerSecret,
    'token'           => $this->token,
    'tokenSecret'    => $this->tokenSecret,
+    'consumer_key'    => $this->consumerKey,
+    'consumer_secret' => $this->consumerSecret,
+    'token_secret'    => $this->tokenSecret
]);
```

"+" - is new string in code

Try in new project with only one dependence:
php composer.phar require stevenmaguire/yelp-php
Problem the same.

**Comment by stevenmaguire** [comment]
@antonkurko Thank you for catching this! I've implemented a few changes that should resolve this issue. These changes can be found in version 1.4.2.

Additionally, there were in fact breaking changes related to the configuration of the client. The client does now prefer the new camelCase configuration keys and previously did not support the legacy snake_case. I have provided a fix for backwards compatibility which will parse snake_case keys and include their camelCase variations automatically.

The README and tests have been updated to reflect the preferred flavor of configuration. 

Please pull 1.4.2 and let me know if the issues you're experiencing are resolved.

**Comment by antonkurko** [comment]
It's perfect. Many thanks
